namespace MarvelPhases.Migrations
{
    using Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<MarvelPhases.Models.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(MarvelPhases.Models.ApplicationDbContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data. E.g.
            //
            //    context.People.AddOrUpdate(
            //      p => p.FullName,
            //      new Person { FullName = "Andrew Peters" },
            //      new Person { FullName = "Brice Lambson" },
            //      new Person { FullName = "Rowan Miller" }
            //    );
            //

            context.Phases.AddOrUpdate(
                p => p.Id,
                new Phase { Id = 1, PhaseName = "Phase 1" },
                new Phase { Id = 2, PhaseName = "Phase 2" },
                new Phase { Id = 3, PhaseName = "Phase 3" }
                );

            context.Movies.AddOrUpdate(
                new Movie { Id = 1, Title = "Iron Man", CollectionNumber = 1, PhaseId = 1, Rating = 8, BoxOffice = 585174222, Description = "Tony Stark. Genius, billionaire, playboy, philanthropist. Son of legendary inventor and weapons contractor Howard Stark. When Tony Stark is assigned to give a weapons presentation to an Iraqi unit led by Lt. Col. James Rhodes, he's given a ride on enemy lines. That ride ends badly when Stark's Humvee that he's riding in is attacked by enemy combatants. He survives - barely - with a chest full of shrapnel and a car battery attached to his heart. In order to survive he comes up with a way to miniaturize the battery and figures out that the battery can power something else. Thus Iron Man is born. He uses the primitive device to escape from the cave in Iraq. Once back home, he then begins work on perfecting the Iron Man suit. But the man who was put in charge of Stark Industries has plans of his own to take over Tony's technology for other matters." },
                new Movie { Id = 2, Title = "The Incredible Hulk", CollectionNumber = 1, PhaseId = 1, Rating = 7, BoxOffice = 263427551, Description = "Depicting the events after the Gamma Bomb. 'The Incredible Hulk' tells the story of Dr Bruce Banner, who seeks a cure to his unique condition, which causes him to turn into a giant green monster under emotional stress.Whilst on the run from military which seeks his capture, Banner comes close to a cure.But all is lost when a new creature emerges; The Abomination." },
                new Movie { Id = 3, Title = "Iron Man 2", CollectionNumber = 2, PhaseId = 1, Rating = 7, BoxOffice = 623933331, Description = "With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press, and the public to share his technology with the military.Unwilling to let go of his invention, Stark, along with Pepper Potts, and James 'Rhodey' Rhodes at his side, must forge new alliances - and confront powerful enemies. "},
                new Movie { Id = 4, Title = "Thor", CollectionNumber = 1, PhaseId = 1, Rating = 7, BoxOffice = 449326618, Description = "The warrior Thor (Hemsworth) is cast out of the fantastic realm of Asgard by his father Odin (Hopkins) for his arrogance and sent to Earth to live among humans. Falling in love with scientist Jane Foster (Portman) teaches Thor much-needed lessons, and his new-found strength comes into play as a villain from his homeland sends dark forces toward Earth." },
                new Movie { Id = 5, Title = "Captain America: The First Avenger", CollectionNumber = 1, PhaseId = 1, Rating = 7, BoxOffice = 370569774, Description = "It is 1942, America has entered World War II, and sickly but determined Steve Rogers is frustrated at being rejected yet again for military service. Everything changes when Dr. Erskine recruits him for the secret Project Rebirth. Proving his extraordinary courage, wits and conscience, Rogers undergoes the experiment and his weak body is suddenly enhanced into the maximum human potential. When Dr. Erskine is then immediately assassinated by an agent of Nazi Germany's secret HYDRA research department (headed by Johann Schmidt, a.k.a. the Red Skull), Rogers is left as a unique man who is initially misused as a propaganda mascot; however, when his comrades need him, Rogers goes on a successful adventure that truly makes him Captain America, and his war against Schmidt begins." },
                new Movie { Id = 6, Title = "Marvel's The Avengers", CollectionNumber = 1, PhaseId = 1, Rating = 8, BoxOffice = 1519557910, Description = "Nick Fury is the director of S.H.I.E.L.D., an international peace-keeping agency. The agency is a who's who of Marvel Super Heroes, with Iron Man, The Incredible Hulk, Thor, Captain America, Hawkeye and Black Widow. When global security is threatened by Loki and his cohorts, Nick Fury and his team will need all their powers to save the world from disaster which is formed by Loki and his team." },
                new Movie { Id = 7, Title = "Iron Man 3", CollectionNumber = 3, PhaseId = 2, Rating = 7, BoxOffice = 1215439994, Description = "Marvel's 'Iron Man 3' pits brash-but-brilliant industrialist Tony Stark/Iron Man against an enemy whose reach knows no bounds. When Stark finds his personal world destroyed at his enemy's hands, he embarks on a harrowing quest to find those responsible. This journey, at every turn, will test his mettle. With his back against the wall, Stark is left to survive by his own devices, relying on his ingenuity and instincts to protect those closest to him. As he fights his way back, Stark discovers the answer to the question that has secretly haunted him: does the man make the suit or does the suit make the man? " },
                new Movie { Id = 8, Title = "Thor: The Dark World", CollectionNumber = 2, PhaseId = 2, Rating = 7, BoxOffice = 644783140, Description = "Thousands of years ago, a race of beings known as Dark Elves tried to send the universe into darkness by using a weapon known as the Aether. Warriors from Asgard stop them but their leader Malekith escapes to wait for another opportunity. The warriors find the Aether and since it cannot be destroyed, they try to hide it. In the present day, Jane Foster awaits the return of Thor although it has been two years since they last saw once another. In the meantime, Thor has been trying to bring peace to the nine realms. Jane discovers an anomaly similar to the one that brought Thor to Earth. She goes to investigate, finds a wormhole, and is sucked into it. Back on Asgard, Thor wishes to return to Earth but his father, Odin refuses to let him. Thor learns from Heimdall, who can see into all of the realms, that Jane disappeared. Thor then returns to Earth just as Jane reappears. However, when some policemen try to arrest her, an unknown energy repulses them. Thor then brings Jane to Asgard to find out what happened to her. When the energy is released again, they discover that when Jane disappeared, she crossed paths with the Aether and it entered her. Malekith, upon sensing that the time to strike is now, seeks out the Aether. He attacks Asgard and Thor's mother Frigga is killed protecting Jane. Odin wants to keep Jane on Asgard so that Malekith will come. Thor disagrees with his plan, so with his cohorts, he decides to take Jane away. He enlists the aid of his brother, Loki. Unfortunately, Loki's motivations remain unknown." },
                new Movie { Id = 9, Title = "Captain America: The Winter Solider", CollectionNumber = 2, PhaseId = 2, Rating = 8, BoxOffice = 714766572, Description = "For Steve Rogers, awakening after decades of suspended animation involves more than catching up on pop culture; it also means that this old school idealist must face a world of subtler threats and difficult moral complexities. That becomes clear when Director Nick Fury is killed by the mysterious assassin, the Winter Soldier, but not before warning Rogers that SHIELD has been subverted by its enemies. When Rogers acts on Fury's warning to trust no one there, he is branded as a traitor by the organization. Now a fugitive, Captain America must get to the bottom of this deadly mystery with the help of the Black Widow and his new friend, The Falcon. However, the battle will be costly for the Sentinel of Liberty, with Rogers finding enemies where he least expects them while learning that the Winter Soldier looks disturbingly familiar." },
                new Movie { Id = 10, Title = "Guardians of the Galaxy", CollectionNumber = 1, PhaseId = 2, Rating = 8, BoxOffice = 774176600, Description = "After stealing a mysterious orb in the far reaches of outer space, Peter Quill from Earth is now the main target of a manhunt led by the villain known as Ronan the Accuser. To help fight Ronan and his team and save the galaxy from his power, Quill creates a team of space heroes known as the 'Guardians of the Galaxy' to save the galaxy." },
                new Movie { Id = 11, Title = "Avengers: Age of Ultron", CollectionNumber = 2, PhaseId = 2, Rating = 7, BoxOffice = 1405413868, Description = "Tony Stark creates the Ultron Program to protect the world, but when the peacekeeping program becomes hostile, The Avengers go into action to try and defeat a virtually impossible enemy together. Earth's mightiest heroes must come together once again to protect the world from global extinction." },
                new Movie { Id = 12, Title = "Ant-Man", CollectionNumber = 1, PhaseId = 2, Rating = 7, BoxOffice = 519445163, Description = "Armed with the astonishing ability to shrink in scale but increase in strength, con-man Scott Lang must embrace his inner-hero and help his mentor, Dr. Hank Pym, protect the secret behind his spectacular Ant-Man suit from a new generation of towering threats. Against seemingly insurmountable obstacles, Pym and Lang must plan and pull off a heist that will save the world." },
                new Movie { Id = 13, Title = "Captain America: Civil War", CollectionNumber = 3, PhaseId = 3, Rating = 8, BoxOffice = 1153304495, Description = "With many people fearing the actions of super heroes, the government decides to push for the Hero Registration Act, a law that limits a hero's actions. This results in a division in The Avengers. Iron Man stands with this Act, claiming that their actions must be kept in check otherwise cities will continue to be destroyed, but Captain America feels that saving the world is daring enough and that they cannot rely on the government to protect the world. This escalates into an all-out war between Team Iron Man (Iron Man, Black Panther, Vision, Black Widow, War Machine, and Spider-Man) and Team Captain America (Captain America, Bucky Barnes, Falcon, Scarlet Witch, Hawkeye, and Ant Man) while a new villain emerges." },
                new Movie { Id = 14, Title = "Doctor Strange", CollectionNumber = 1, PhaseId = 3, Rating = 7, BoxOffice = 677718395, Description = "Marvel's 'Doctor Strange' follows the story of the talented neurosurgeon Doctor Stephen Strange who, after a tragic car accident, must put ego aside and learn the secrets of a hidden world of mysticism and alternate dimensions. Based in New York City's Greenwich Village, Doctor Strange must act as an intermediary between the real world and what lies beyond, utilising a vast array of metaphysical abilities and artifacts to protect the Marvel Cinematic Universe." },
                new Movie { Id = 15, Title = "Guardians of the Galaxy Vol. 2", CollectionNumber = 2, PhaseId = 3, Rating = 8, BoxOffice = 863756051, Description = "After saving Xandar from Ronan's wrath, the Guardians are now recognized as heroes. Now the team must help their leader Star Lord (Chris Pratt) uncover the truth behind his true heritage. Along the way, old foes turn to allies and betrayal is blooming. And the Guardians find that they are up against a devastating new menace who is out to rule the galaxy." },
                new Movie { Id = 16, Title = "Spider-Man: Homecoming", CollectionNumber = 1, PhaseId = 3, Rating = 7, BoxOffice = 880166924, Description = "Thrilled by his experience with the Avengers, Peter returns home, where he lives with his Aunt May, under the watchful eye of his new mentor Tony Stark, Peter tries to fall back into his normal daily routine - distracted by thoughts of proving himself to be more than just your friendly neighborhood Spider-Man - but when the Vulture emerges as a new villain, everything that Peter holds most important will be threatened." },
                new Movie { Id = 17, Title = "Thor: Ragnarok", CollectionNumber = 3, PhaseId = 3, Rating = 8, BoxOffice = 853977126, Description = "Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his homeworld and the end of Asgardian civilization, at the hands of an all-powerful new threat, the ruthless Hela." },
                new Movie { Id = 18, Title = "Black Panther", CollectionNumber = 1,  PhaseId = 3, Rating = 7, BoxOffice = 1346601031, Description = "After the events of Captain America: Civil War, King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne from factions within his own country. When two foes conspire to destroy Wakanda, the hero known as Black Panther must team up with C.I.A. agent Everett K. Ross and members of the Dora Milaje, Wakandan special forces, to prevent Wakanda from being dragged into a world war." },
                new Movie { Id = 19, Title = "Avengers: Infinity War", CollectionNumber = 3, PhaseId = 3, Rating = 9, BoxOffice = 2043465918, Description = "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain." },
                new Movie { Id = 20, Title = "Ant-Man & the Wasp", CollectionNumber = 2, PhaseId = 3, Rating = 7, BoxOffice = 356866453, Description = "In the aftermath of 'Captain America: Civil War,' Scott Lang grapples with the consequences of his choices as both a Super Hero and a father. As he struggles to re-balance his home life with his responsibilities as Ant-Man, he's confronted by Hope van Dyne and Dr. Hank Pym with an urgent new mission. Scott must once again put on the suit and learn to fight alongside The Wasp as the team works together to uncover secrets from their past." }
                );

            context.Series.AddOrUpdate(
                new Series { Id = 1, Title = "Agent Carter", SeriesNumber = 1, PhaseId = 1, Rating = 8, TvService = "ABC", Description = "The war is over and almost everyone has experienced a loss. Agent Peggy Carter has lost the love of her life. To top it off, when billionaire Howard Stark is accused of Treason, he secretly employs her to clear his name. With the help of Stark's butler, she embarks on a whimsical journey full of deceit, murder and controversy with a side of wise-cracking roommates." },
                new Series { Id = 2, Title = "Agent Carter", SeriesNumber = 2, PhaseId = 1, Rating = 8, TvService = "ABC", Description = "The war is over and almost everyone has experienced a loss. Agent Peggy Carter has lost the love of her life. To top it off, when billionaire Howard Stark is accused of Treason, he secretly employs her to clear his name. With the help of Stark's butler, she embarks on a whimsical journey full of deceit, murder and controversy with a side of wise-cracking roommates." },
                new Series { Id = 3, Title = "Agent of S.H.I.E.L.D", SeriesNumber = 1, PhaseId = 2, Rating = 7, TvService = "ABC", Description = "After the Battle of New York, the world has changed. It now knows not only about the Avengers, but also the powerful menaces that require those superheroes and more to face them. In response, Phil Coulson of the Strategic Homeland Intervention, Enforcement and Logistics Division assembles an elite covert team to find and deal with these threats wherever they are found. With a world rapidly becoming more bizarre and dangerous than ever before as the supervillains arise, these agents of S.H.I.E.L.D. are ready to take them on." },
                new Series { Id = 4, Title = "Daredevil", SeriesNumber = 1, PhaseId = 2, Rating = 9, TvService = "Netflix", Description = "As a child Matt Murdock was blinded by a chemical spill in a freak accident. Instead of limiting him it gave him superhuman senses that enabled him to see the world in a unique and powerful way. Now he uses these powers to deliver justice, not only as a lawyer in his own law firm, but also as vigilante at night, stalking the streets of Hell's Kitchen as Daredevil, the man without fear." },
                new Series { Id = 5, Title = "Jessica Jones", SeriesNumber = 1, PhaseId = 2, Rating = 8, TvService = "Netflix", Description = "Ever since her short-lived stint as a superhero ended in tragedy, Jessica Jones has been rebuilding her personal life and career as a hot-tempered, sardonic private detective in Hell's Kitchen, New York City. Plagued by self-loathing and a wicked case of PTSD, Jessica battles demons from within and without, using her extraordinary abilities as an unlikely champion for those in need... especially if they're willing to cut her a check." },
                new Series { Id = 6, Title = "Agent of S.H.I.E.L.D", SeriesNumber = 2, PhaseId = 2, Rating = 8, TvService = "ABC", Description = "The war is over and almost everyone has experienced a loss. Agent Peggy Carter has lost the love of her life. To top it off, when billionaire Howard Stark is accused of Treason, he secretly employs her to clear his name. With the help of Stark's butler, she embarks on a whimsical journey full of deceit, murder and controversy with a side of wise-cracking roommates." },
                new Series { Id = 7, Title = "Daredevil", SeriesNumber = 2, PhaseId = 2, Rating = 9, TvService = "Netflix", Description = "As a child Matt Murdock was blinded by a chemical spill in a freak accident. Instead of limiting him it gave him superhuman senses that enabled him to see the world in a unique and powerful way. Now he uses these powers to deliver justice, not only as a lawyer in his own law firm, but also as vigilante at night, stalking the streets of Hell's Kitchen as Daredevil, the man without fear." },
                new Series { Id = 8, Title = "Luke Cage", SeriesNumber = 1, PhaseId = 2, Rating = 7, TvService = "Netflix", Description = "After a sabotaged experiment leaves him with super strength and unbreakable skin, Luke Cage becomes a fugitive trying to rebuild his life in modern day Harlem, New York City. But he is soon pulled out of the shadows and must fight a battle for the heart of his city - forcing him to confront a past he had tried to bury." },
                new Series { Id = 9, Title = "Agent of S.H.I.E.L.D", SeriesNumber = 3, PhaseId = 3, Rating = 8, TvService = "ABC", Description = "The war is over and almost everyone has experienced a loss. Agent Peggy Carter has lost the love of her life. To top it off, when billionaire Howard Stark is accused of Treason, he secretly employs her to clear his name. With the help of Stark's butler, she embarks on a whimsical journey full of deceit, murder and controversy with a side of wise-cracking roommates." },
                new Series { Id = 10, Title = "Iron Fist", SeriesNumber = 1, PhaseId = 3, Rating = 7, TvService = "Netflix", Description = "Danny Rand returns to New York City after being missing for years, trying to reconnect with his past and his family legacy. He fights against the criminal element corrupting his world around him with his incredible kung-fu mastery and ability to summon the awesome power of the fiery Iron Fist" },
                new Series { Id = 11, Title = "The Defenders", SeriesNumber = 1, PhaseId = 3, Rating = 7, TvService = "Netflix", Description = "'Marvel's The Defenders' follows Daredevil, Jessica Jones, Luke Cage and Iron Fist. A quartet of singular heroes with one common goal - to save New York City. This is the story of four solitary figures, burdened with their own personal challenges, who realize they just might be stronger when teamed together."},
                new Series { Id = 12, Title = "Agent of S.H.I.E.L.D", SeriesNumber = 4, PhaseId = 3, Rating = 8, TvService = "ABC", Description = "The war is over and almost everyone has experienced a loss. Agent Peggy Carter has lost the love of her life. To top it off, when billionaire Howard Stark is accused of Treason, he secretly employs her to clear his name. With the help of Stark's butler, she embarks on a whimsical journey full of deceit, murder and controversy with a side of wise-cracking roommates." },
                new Series { Id = 13, Title = "The Inhumans", SeriesNumber = 1, PhaseId = 3, Rating = 5, TvService = "ABC", Description = "An isolated community of superhumans fight to protect themselves." },
                new Series { Id = 14, Title = "The Punisher", SeriesNumber = 1, PhaseId = 3, Rating = 9, TvService = "Netflix", Description = "After exacting revenge on those responsible for the death of his wife and children, Frank Castle uncovers a conspiracy that runs far deeper than New York's criminal underworld. Now known throughout the city as The Punisher, he must discover the truth about injustices that affect more than his family alone." },
                new Series { Id = 15, Title = "The Runaway's", SeriesNumber = 1, PhaseId = 3, Rating = 7, TvService = "Hulu", Description = "Follows a group of six teenagers in the Marvel universe - Nico Minoru, Karolina Dean, Molly Hernandez, Chase Stein, Alex Wilder, and Gertrude Yorkes - who discover that their parents are secretly members of a super-villain cabal called The Pride. After deciding they're no longer safe in their own homes, the kids go on the run. In the midst of hiding from their elders, the teens learn about themselves and become a family of their own." },
                new Series { Id = 16, Title = "Agent of S.H.I.E.L.D", SeriesNumber = 5, PhaseId = 3, Rating = 8, TvService = "ABC", Description = "The war is over and almost everyone has experienced a loss. Agent Peggy Carter has lost the love of her life. To top it off, when billionaire Howard Stark is accused of Treason, he secretly employs her to clear his name. With the help of Stark's butler, she embarks on a whimsical journey full of deceit, murder and controversy with a side of wise-cracking roommates." },
                new Series { Id = 17, Title = "Jessica Jones", SeriesNumber = 2, PhaseId = 3, Rating = 8, TvService = "Netflix", Description = "Ever since her short-lived stint as a superhero ended in tragedy, Jessica Jones has been rebuilding her personal life and career as a hot-tempered, sardonic private detective in Hell's Kitchen, New York City. Plagued by self-loathing and a wicked case of PTSD, Jessica battles demons from within and without, using her extraordinary abilities as an unlikely champion for those in need... especially if they're willing to cut her a check." },
                new Series { Id = 18, Title = "Luke Cage", SeriesNumber = 2, PhaseId = 3, Rating = 7, TvService = "Netflix", Description = "After a sabotaged experiment leaves him with super strength and unbreakable skin, Luke Cage becomes a fugitive trying to rebuild his life in modern day Harlem, New York City. But he is soon pulled out of the shadows and must fight a battle for the heart of his city - forcing him to confront a past he had tried to bury." }
                );
                }
    }
}
